name: Publish new Release

on: workflow_dispatch

permissions:
  contents: write

jobs:
  get-release-version:
    runs-on: ubuntu-latest
    outputs:
      release-version: ${{ steps.set-release-version.outputs.result }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        id: set-release-version
        with:
          result-encoding: string
          script: |
            const { owner, repo } = context.repo
            const version = require("./package.json").version
            const versionTag = `v${version}`
            return versionTag
  publish_package:
    runs-on: ubuntu-latest
    needs: get-release-version
    permissions:
      contents: write
      id-token: write
    environment: release
    steps:
      - uses: actions/checkout@v4

      - name: Install modules
        run: yarn install

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: Create NPM release
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub release
        uses: actions/github-script@v7
        with:
          script: |
            const defaultBranch = "${{ github.event.repository.default_branch }}"
            const versionTag = "${{ needs.get-release-version.outputs.release-version }}"
            await require('./scripts/release').release({ github, context, defaultBranch, versionTag })